adding create and delete db commands
GabrielPAntoniolli/Twitter-clone-nodejs pull request #4
Opened 2022-10-07 20:27 UTC by GabrielPAntoniolli

Resolve #1

2022-10-09 02:44 UTC, lukas8219 requested changes
Ok. Criou o Delete.

Agora tu precisa adicionar as rotas e linkar os  métodos com as rotas.

2022-10-09 02:44 UTC, lukas8219 commented on app.js
> +
Ok. Mas que tal movar esses métodos todos para uma classe só? Um Controller??

2022-10-09 02:44 UTC, lukas8219 commented on app.js
>  })
Não vai adicionar a rotas?

2022-10-10 07:32 UTC, GabrielPAntoniolli commented
passei as funcoes para um controller class, vou fazer  a autenticacao agora

2022-10-10 12:32 UTC, lukas8219 requested changes

2022-10-10 12:32 UTC, lukas8219 commented on dbController.js
> +
Boa. É isso mesmo, mas vamos pensar na semântica.

O que é `DbController`?  DatabaseController??

Controller geralmente se refere a algum `Resource` ou algum objeto importante pro teu negócio.

Nesse caso, seria o Usuário certo?

Outro ponto, vamos preferir usar classes.

2022-10-10 12:32 UTC, lukas8219 commented on signin.html
> +</html>
Tu vai querer usar React? A gente pode dar um jeito de renderizar o React pelo Node. Nunca fiz, mas é possível.

Ou tu quer uma pagina simples, ao menos de início?

2022-10-10 12:32 UTC, lukas8219 commented on app.js
> +
Proxima etapa, depois de criado o Controller, precisamo de um Router que vai mapear as rotas à um método do Controller.

2022-10-11 15:46 UTC, lukas8219 requested changes

2022-10-11 15:46 UTC, lukas8219 commented on userController.js
> +const dbSchemas = require('./repository/dbSchemas');
Agora sim!

Move esses controllers para uma pasta.

`src/controllers`.

Also, transforma eles em uma classe.

class UserController {} ....

2022-10-11 15:46 UTC, lukas8219 commented on app.js
> +    };
Aqui tu pode usar uma técnica chamada `destructuring`. Também, sempre tenha preferencia por `const` do que `let`.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

2022-10-11 15:46 UTC, lukas8219 commented on app.js
> +});
isso aqui ta OK pra agora. Mas vamos precisar rever essa lógica depois caso tu queria usar EJS ou React.

2022-10-12 12:29 UTC, GabrielPAntoniolli commented on userController.js
> +const dbSchemas = require('./repository/dbSchemas');
done

2022-10-12 12:29 UTC, GabrielPAntoniolli commented on app.js
> +    };
done

2022-10-12 12:30 UTC, GabrielPAntoniolli commented on app.js
> +});
quero fazer com react depois, num outro server.
mas primeiro preciso fazer a autenticacao do usuario funcionar

2022-10-12 15:45 UTC, lukas8219 commented on app.js
> +});
Tu pode usar o Postman...Nao precisar usar nada na UI

2022-10-12 15:52 UTC, lukas8219 requested changes
Ta ficando bom!!

2022-10-12 15:52 UTC, lukas8219 commented on app.js
> +  await mongoose.connect(process.env.DB_CONNECTION).catch(err => console.log(err));
Nice

2022-10-12 15:52 UTC, lukas8219 commented on app.js
> +  secret: 'keyboard cat',
move pro `.dotenv`

2022-10-12 15:52 UTC, lukas8219 commented on app.js
> +    return cb(null, user);
Aqui é o momento de tu procurar no banco e criar o user....

Se nao, ele vai chegar no Request do Express apenas o ID

2022-10-12 15:52 UTC, lukas8219 commented on app.js
> +    controller.User.findOne({ email: email }, function (err, user) {
controller.findByEmail(email);

2022-10-12 15:52 UTC, lukas8219 commented on app.js
> +  passport.authenticate('local', { failureRedirect: '/' }),
Also, eu preciso dar uma olhada nesse LocalStrategy... A ideia é ser algo mais generalista, e nao ter que chamar o Middleware em toda rota

2022-10-12 15:52 UTC, lukas8219 commented on src/controller/UserController.js
> +    }
Nao usa `Arrow Function` em classes. Sempre prefere function normal.

Ou seja, addUser(email, password) {}.

2022-10-12 15:52 UTC, lukas8219 commented on src/controller/UserController.js
> +        let newUser = new this.User({
Lembra.... `const` e `let`...Prefira `const`

2022-10-12 15:52 UTC, lukas8219 commented on src/controller/UserController.js
> +        newUser.save(err => {if(err){ console.log(err)} else { console.log("User persisted successfully");}});
Precisamos sempre de um retorno em controllers....Pensa que vai ser isso que vai ser devolvido pro usuário...

Nunca dependa do `implicit return`... deixa explícito.

2022-10-12 15:52 UTC, lukas8219 commented on src/controller/UserController.js
> +    findUserByEmail = email => { this.User.findOne({email: email}, (err, foundUser)=>{
Aqui tu ta usando muito callback.

Existe uma expressão chamada `Callback Hell` em JS. http://callbackhell.com/

Dá uma olhada no pacote `promisify` do Node. Que transforma callback em Promise. E tenha sempre preferencia por ele.

2022-10-13 12:24 UTC, lukas8219 requested changes

2022-10-13 12:24 UTC, lukas8219 commented on src/controller/UserController.js
> +}
Ta bonitão... Mas transforma em Promises sempre...

`return new Promise((res, rej) => {.... res(cb)`.

Seria algo do tipo `return new Promise((res, rej) => { this.User.find({}, res) })`

POREM, se nao me engano o mongoose ja tem suporte pra promise ein...Nao é obrigatório usar CB...

2022-10-24 22:47 UTC, lukas8219 commented on src/controller/UserController.js
> +                    }}
Tenta sempre retornar o resultado pro cliente

2022-10-24 22:47 UTC, lukas8219 commented on src/controller/UserController.js
> +                console.log("error deleting user")
Dá o throw no error.

2022-11-07 15:16 UTC, lukas8219 approved these changes

2022-11-07 15:42 UTC, merged